#ifndef _INTERFACE_
#define _INTERFACE_

#define _CELL_
#undef _CELL_

#define ENABLE		1
#define DISABLE	0

typedef enum ENUM_STRING_ID
{
	TS_CELLLOCK_DECTE = 0,
	TS_SWITCH_TO_GSM_WAIT,
	TS_QUERY_GSM_CELL_WAIT,
	TS_SWITCH_TO_NORMAL_MODE,
	TS_GET_IMEI,
	TS_GET_IMEI_WAIT,
	TS_INIT,
	TS_IDLE,
	TS_USER_IDLE,
	TS_USER_INPUT_PUK,
	TS_USER_DETEC_PUK_WAIT,
	TS_LOCK_CARD_DETECT_WAIT,
	TS_LOCK_CARD_ENABLE_WAIT,
	TS_UNLOCK_CARD_WAIT,
	TS_MACHINE_CARD_BIND_WAIT,
	TS_USER_DISABLE_LOCK_CARD_WAIT,
	TS_USER_PIN_MODIFY_WAIT,
	TS_PIN_ENABLE,
	TS_PIN_DISABLE,
	TS_PIN_MODIFY,
	TS_AUTO_UNLOCKCARD_WAITING,
	TS_AUTO_LOCKCARDENABLE_WAITING,
	TS_AUTO_LOCKCARDDISABLE_WAITING,
	TS_AUTO_PINMODIFY_WAITING,
	TS_CELL_ENABLE,
	TS_CELL_ENABLE_WAIT,
	TS_CELL_DISABLE,
	TS_GSM_WAITING,
	TS_GSM_SCANCELL,
	TS_GSM_SCANCELL_WAITE,
	TS_NO_SIM_CARD,
	TS_ERROR,
}STRING_ID;

typedef struct
{
	STRING_ID    main_interface_index;    //Ö÷²Ëµ¥
	
}ST_MENU;

ST_MENU      st_menu;
void *interface_active_handler(void *arg);
void *send_sms_handler(void *arg);

#endif

