/*
** Copyright (c) 2009-2015 by Silicon Laboratories
**
** $Id: si_voice_version.c 5013 2015-05-15 17:29:22Z nizajerk $
**
** si_voice_version.c
** ProSLIC API Version
**
** Author(s): 
** cdp
**
** Distributed by: 
** Silicon Laboratories, Inc
**
** This file contains proprietary information.	 
** No dissemination allowed without prior written permission from
** Silicon Laboratories, Inc.
** 
** THIS FILE IS AUTOGENERATED - DO NOT MODIFY
**
*/

char *SiVoiceAPIVersion = "8.00rc3";
