watchdog_monitor: watchdog_monitor.o
	$(CC) $(LDFLAGS) watchdog_monitor.o -o watchdog_monitor
watchdog_monitor.o: watchdog_monitor.c
	$(CC) $(CFLAGS) -c watchdog_monitor.c

clean:
	rm *.o watchdog_monitor




